// Single source of truth for branches. Acronym is used in ticket/incident numbers (e.g. D01-000001, INC-D01-000001).
// 'ALL' is a special assignment meaning user has access to every branch; it is not used in ticket numbers.
module.exports.BRANCHES = [
  { acronym: 'ALL', name: 'All Branches' },
  { acronym: 'A1P', name: 'A1+ - Multifood Packaging, Inc.' },
  { acronym: 'D01', name: 'D01 – DISNEY 1' },
  { acronym: 'D02', name: 'D02 – DISNEY 2' },
  { acronym: 'D03', name: 'D03 – DISNEY 3' },
  { acronym: 'D04', name: 'D04 – DISNEY 4' },
  { acronym: 'D05', name: 'D05 – DISNEY 5' },
  { acronym: 'D06', name: 'D06 – DISNEY 6' },
  { acronym: 'D07', name: 'D07 – DISNEY 7' },
  { acronym: 'D08', name: 'D08 – DISNEY 8' },
  { acronym: 'D09', name: 'D09 – DISNEY 9' },
  { acronym: 'DGN', name: 'DGN – DONGGUAN' },
  { acronym: 'EUA', name: 'EUA – EURASIA' },
  { acronym: 'HMF', name: 'HMF – Happy Alliance Mono Film, Inc.' },
  { acronym: 'HBO', name: 'HBO – HASBRO' },
  { acronym: 'MOR', name: 'MOR – ONE MARANAO MAIN' },
  { acronym: 'OMO', name: 'OMO – ONE MARANAO' },
  { acronym: 'MTL', name: 'MTL – MATTEL' },
  { acronym: 'PLA', name: 'PLA – PERLANDIA' },
  { acronym: 'SHI', name: 'SHI – SHANGHAI' },
  { acronym: 'SPI', name: 'SPI – Starkson Packaging INC.' },
  { acronym: 'SII', name: 'SII – STARKSON INDUSTRIES INC.' },
  { acronym: 'SM1', name: 'SM1 – STARKSON INDUSTRIES INC.' },
  { acronym: 'WNR', name: 'WNR – WARNER' },
  { acronym: 'STO', name: 'STO – SITIO' },
]
